stages:
  train_episodic:
    foreach:
      - resnet18
      - mobilenet
    do:
      cmd: python -m stages.train_episodic
        ${item}
        --output-model ${models_dir}/${item}_episodic.tar
        --n-epochs 2
        &> ${logs_dir}/train_episodic_${item}.out
      deps:
        - stages/train_episodic.py
      outs:
        - ${models_dir}/${item}_episodic.tar
        - ${logs_dir}/train_episodic_${item}.out

  train_classic:
    foreach:
      - resnet18
      - mobilenet
    do:
      cmd: python -m stages.train_classic
        ${item}
        --output-model ${models_dir}/${item}_classic.tar
        --n-epochs 2
        &> ${logs_dir}/train_classic_${item}.out
      deps:
        - stages/train_classic.py
      outs:
        - ${models_dir}/${item}_classic.tar
        - ${tb_logs_dir}
        - ${logs_dir}/train_classic_${item}.out
