stages:
  train_episodic:
    foreach:
      - backbone: resnet18
        dataset: cifar
      - backbone: resnet34
        dataset: cifar
      - backbone: resnet18
        dataset: mini_imagenet
      - backbone: resnet34
        dataset: mini_imagenet
    do:
      cmd: python -m stages.train_episodic
        ${item.backbone}
        ${item.dataset}
        --output-model ${models_dir}/${item.backbone}_${item.dataset}_episodic.tar
        --n-epochs 240
        --n-way 32
        --n-query 15
        --n-tasks-per-epoch 75
        --feature-dimension 512
        --tb-log-dir ${tb_logs_dir}/${item.backbone}_${item.dataset}_episodic
        &> ${logs_dir}/train_episodic_${item.backbone}_${item.dataset}.out
      deps:
        - stages/train_episodic.py
      outs:
        - ${models_dir}/${item.backbone}_${item.dataset}_episodic.tar
        - ${tb_logs_dir}/${item.backbone}_${item.dataset}_episodic
        - ${logs_dir}/train_episodic_${item.backbone}_${item.dataset}.out

  train_classic:
    foreach:
      - resnet18
      - resnet34
    do:
      cmd: python -m stages.train_classic
        ${item}
        --output-model ${models_dir}/${item}_classic.tar
        --n-epochs 200
        --batch-size 512
        --tb-log-dir ${tb_logs_dir}/${item}_classic
        &> ${logs_dir}/train_classic_${item}.out
      deps:
        - stages/train_classic.py
      outs:
        - ${models_dir}/${item}_classic.tar
        - ${tb_logs_dir}/${item}_classic
        - ${logs_dir}/train_classic_${item}.out
