stages:
  train_episodic:
    foreach:
      - resnet18
      - mobilenet
    do:
      cmd: python -m stages.train_episodic
        ${item}
        --output-model ${models_dir}/${item}_episodic.tar
        --n-epochs 50
        --n-query 20
        --n-tasks-per-epoch 250
        --tb-log-dir ${tb_logs_dir}/${item}_episodic
        &> ${logs_dir}/train_episodic_${item}.out
      deps:
        - stages/train_episodic.py
      outs:
        - ${models_dir}/${item}_episodic.tar
        - ${tb_logs_dir}/${item}_episodic
        - ${logs_dir}/train_episodic_${item}.out

  train_classic:
    foreach:
      - resnet18
      - mobilenet
    do:
      cmd: python -m stages.train_classic
        ${item}
        --output-model ${models_dir}/${item}_classic.tar
        --n-epochs 100
        --batch-size 256
        --tb-log-dir ${tb_logs_dir}/${item}_classic
        &> ${logs_dir}/train_classic_${item}.out
      deps:
        - stages/train_classic.py
      outs:
        - ${models_dir}/${item}_classic.tar
        - ${tb_logs_dir}/${item}_classic
        - ${logs_dir}/train_classic_${item}.out
