stages:
  train_classic:
    foreach: ${model_grid}
    do:
      cmd: python -m stages.train_classic
        ${item.backbone}
        ${item.dataset}
        --output-model ${models_dir}/${item.backbone}_${item.dataset}_classic.tar
        --n-epochs ${training_setup.n_epochs}
        --learning-rate ${training_setup.learning_rate}
        --scheduler-milestones ${training_setup.scheduler_milestones}
        --scheduler-gamma ${training_setup.scheduler_gamma}
        --batch-size ${training_setup.batch_size}
        --tb-log-dir ${tb_logs_dir}/${item.backbone}_${item.dataset}_classic
        &> ${logs_dir}/train_classic_${item.backbone}_${item.dataset}.out
      deps:
        - stages/train_classic.py
      outs:
        - ${models_dir}/${item.backbone}_${item.dataset}_classic.tar
        - ${tb_logs_dir}/${item.backbone}_${item.dataset}_classic
        - ${logs_dir}/train_classic_${item.backbone}_${item.dataset}.out

  compute_features:
    foreach: ${features_grid}
    do:
      cmd: python -m stages.compute_features
        ${item.backbone}
        ${item.dataset}
        ${models_dir}/${item.backbone}_${item.dataset}_classic.tar
        --split ${item.split}
        &> ${logs_dir}/compute_features_${item.dataset}_${item.split}_${item.backbone}_classic.out
      deps:
        - stages/compute_features.py
        - ${models_dir}/${item.backbone}_${item.dataset}_classic.tar
      outs:
        - ${features_dir}/${item.dataset}/${item.split}/${item.backbone}_${item.dataset}_classic.pickle
        - ${logs_dir}/compute_features_${item.dataset}_${item.split}_${item.backbone}_classic.out
