stages:
  compute_features:
    foreach: ${grid}
    do:
      cmd: python compute_features.py
        ${key}
        ${item.weights}
      deps:
        - compute_features.py
        - ${item.weights}
      outs:
        - data/features/${key}.pickle
