grid:
  mini_imagenet:
    weights: data/models/tadam_resnet12_mini_imagenet.tar
  tiered_imagenet:
    weights: data/models/tadam_resnet12_tiered_imagenet.tar

backbone: src.tadam_resnet.tadam_res12
batch_size: 1024
n_workers: 20
device: cuda

