transforms:
  AlternateCentering:
    current_params: {1: {'lambda_': 1.0, 'lr': 0.1, 'n_iter': 100},
                     5: {'lambda_': 1.0, 'lr': 0.1, 'n_iter': 100}}
    tuning:
      hparams2tune: ['lambda_', 'lr']
      hparam_values: [[0.5, 0.75, 1.0, 1.25, 1.5], [0.1, 0.5, 1.0]]