transforms:
  AlternateCentering:
    current_params: {1: {'lambda_': 10.0, 'lr': 10, 'n_iter': 20, 'init': 'mean', 'n_neighbors': 1},
                     5: {'lambda_': 10.0, 'lr': 10, 'n_iter': 20, 'init': 'mean', 'n_neighbors': 5}}
    tuning:
      hparams2tune: ['lambda_', 'lr', 'n_neighbors', 'n_iter']
      hparam_values: {1: [[1.0, 5.0, 10.0], [0.1, 1.0, 10.0], [1, 2, 3, 4], [5, 10, 15]],
                      5: [[1.0, 5.0, 10.0], [0.1, 1.0, 10.0], [3, 5, 7, 10], [5, 10, 15]]}

  EntropicCentering:
    current_params: {1: {'lambda_': 1, 'lr': 0.1, 'n_iter': 100, 'init': 'base', 'n_neighbors': 2},
                    5: {'lambda_': 1, 'lr': 0.1, 'n_iter': 100, 'init': 'base', 'n_neighbors': 10}}
    tuning:
      hparams2tune: ['lambda_', 'lr', 'n_iter', 'init', 'n_neighbors']
      hparam_values: [[2., 3., 4., 5.], [0.1, 1.0], [100], ['base'], [5]]